=== horno1337/zdaj-se-pjatk-data/schemas/subject-patch.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "subject-patch",
  "title": "Data Item",
  "type": "object",
  "properties": {
    "question": {
      "$id": "#root/question",
      "title": "Question",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": 0
    },
    "numberOfComments": {
      "$id": "#root/numberOfComments",
      "title": "Number of Comments",
      "type": "integer",
      "default": 0
    },
    "answers": {
      "$id": "#root/answers",
      "title": "Answers",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/answers/items",
        "title": "Items",
        "type": "object",
        "required": ["answer", "correct"],
        "properties": {
          "answer": {
            "$id": "#root/answers/items/answer",
            "title": "Answer",
            "type": "string",
            "default": ""
          },
          "correct": {
            "$id": "#root/answers/items/correct",
            "title": "Correct",
            "type": "boolean",
            "default": true
          },
          "isMarkdown": {
            "$id": "#root/answers/items/isMarkdown",
            "title": "Is Markdown",
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
          }
        },
        "required": ["author", "comment", "date"]
      }
    },
    "contributors": {
      "$id": "#root/contributors",
      "title": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "createdAt": {
      "$id": "#root/createdAt",
      "title": "Created At",
      "type": "integer",
      "default": 0
    },
    "isMarkdown": {
      "$id": "#root/isMarkdown",
      "title": "Is Markdown",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["question", "id", "createdAt"]
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-57-1cfe2bde-b5b0-4098-a482-c6c71d684db8.patch.json
{
  "question": "Multi-aspect inheritance is the same as multi-inheritance.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Multi-aspect inheritance is different from multi-inheritance.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-57-1cfe2bde-b5b0-4098-a482-c6c71d684db8",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-132-aed05aba-bd52-4855-ae2b-bd72299e4245.patch.json
{
  "question": "You do not have to watch your users during the usability tests - just listen to their comments.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "User comments may be misleading. Therefore, it is important to observe their behavior.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-132-aed05aba-bd52-4855-ae2b-bd72299e4245",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-67-0f4e9c5f-b81b-4c73-91af-b5cb6cc15fac.patch.json
{
  "question": "The basic principle used to implement constraints is to create public attributes and private methods.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "The basic principle used to implement constraints is to create private attributes and public methods (not vice versa)",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-67-0f4e9c5f-b81b-4c73-91af-b5cb6cc15fac",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/abd/z-09-628d20e0-e5b4-4c3b-8d35-f33535585fda.patch.json
{
  "question": "Zaznacz poprawne stwierdzenia dotyczące opcji \"shrink\" w MS SQL Server",
  "isMarkdown": true,
  "comments": [],
  "answers": [
    {
      "answer": "Może zmniejszyć fizyczny rozmiar pliku z danymi",
      "correct": false
    },
    {
      "answer": "Może zmniejszyć fizyczny rozmiar pliku z dziennikiem transakcji",
      "correct": false
    },
    {
      "answer": "Usuwa nieaktywne transakcje z dziennika transakcji",
      "correct": false
    },
    {
      "answer": "Dokonuje kompresji danych w plikach *.mdf podobnej do tej stosowanej w narzędziach do archiwizacji (np. ZIP lub RAR)",
      "correct": false
    }
  ],
  "id": "z-09-628d20e0-e5b4-4c3b-8d35-f33535585fda",
  "createdAt": 1657199812909,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-150-b48c5e0e-ed19-4e94-af93-f7022f8d7a75.patch.json
{
  "question": "Adding String instead of objects to the control decreases the performance of the application and increases the required developer workload.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Of course, adding String instead of objects to the control decreases application performance and increases the developer's workload. This is because the object needs to be converted to text and subsequently searched for in the extent.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-150-b48c5e0e-ed19-4e94-af93-f7022f8d7a75",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-116-7e263209-7662-45d0-82eb-739b5f8807de.patch.json
{
  "question": "The main reason for using ORM tools is to improve the performance of BD access.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "The basic premise of ORM is to make it easier (transparent) to work with any data source.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-116-7e263209-7662-45d0-82eb-739b5f8807de",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-14-e389fd75-41d2-449d-980b-ee7c7a5d302c.patch.json
{
  "question": "An optional and repetitive attribute may use ArrayList.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "The ArrayList collection may not have any elements, so it is suitable for implementation of the optional attribute.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-14-e389fd75-41d2-449d-980b-ee7c7a5d302c",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-56-277b3a7a-d276-4988-a2fc-adbc9a4685bc.patch.json
{
  "question": "The operation propagation causes the business code of the method to be in a single place.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Thanks to the propagation of the operation, the business code is located in one method, and the rest of the code only calls it.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-56-277b3a7a-d276-4988-a2fc-adbc9a4685bc",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}
