=== horno1337/zdaj-se-pjatk-data/schemas/subject-patch.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "subject-patch",
  "title": "Data Item",
  "type": "object",
  "properties": {
    "question": {
      "$id": "#root/question",
      "title": "Question",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": 0
    },
    "numberOfComments": {
      "$id": "#root/numberOfComments",
      "title": "Number of Comments",
      "type": "integer",
      "default": 0
    },
    "answers": {
      "$id": "#root/answers",
      "title": "Answers",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/answers/items",
        "title": "Items",
        "type": "object",
        "required": ["answer", "correct"],
        "properties": {
          "answer": {
            "$id": "#root/answers/items/answer",
            "title": "Answer",
            "type": "string",
            "default": ""
          },
          "correct": {
            "$id": "#root/answers/items/correct",
            "title": "Correct",
            "type": "boolean",
            "default": true
          },
          "isMarkdown": {
            "$id": "#root/answers/items/isMarkdown",
            "title": "Is Markdown",
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
          }
        },
        "required": ["author", "comment", "date"]
      }
    },
    "contributors": {
      "$id": "#root/contributors",
      "title": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "createdAt": {
      "$id": "#root/createdAt",
      "title": "Created At",
      "type": "integer",
      "default": 0
    },
    "isMarkdown": {
      "$id": "#root/isMarkdown",
      "title": "Is Markdown",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["question", "id", "createdAt"]
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-69-bdcc8a11-73f0-414a-a8e7-d49cbb8c3b2f.patch.json
{
  "question": "Implementing {unique} with the class attribute Set will improve performance at the expense of memory.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "The Set container will speed up the search, but of course it will take extra memory.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-69-bdcc8a11-73f0-414a-a8e7-d49cbb8c3b2f",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-03-3e07c723-7034-40e5-b9b6-9a1551687be0.patch.json
{
  "question": "Class extent and object mean the same thing.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Class extent is a collection of all objects.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-03-3e07c723-7034-40e5-b9b6-9a1551687be0",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-49-32c5f348-765b-4223-9cae-5b40494440c9.patch.json
{
  "question": "In the abstract class there can be both abstract and concrete methods",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "In the abstract class there can be both abstract and concrete methods.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-49-32c5f348-765b-4223-9cae-5b40494440c9",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/abd/z-13-316a3e87-45b8-4a87-be3d-9b9f83cb63ce.patch.json
{
  "question": "W MS SQL Server wykonywana była pełna kopia zapasowa nocy z soboty na niedzielę. Następnie co godzinę każdego dnia w godz. 8-16 wykonywana była kopia dziennika transakcji. Awaria nastąpiła w środę o 12:01. Których kopii zapasowych i w jakiej kolejności użyjesz, aby odtworzyć tą bazę danych?",
  "isMarkdown": true,
  "comments": [],
  "answers": [
    {
      "answer": "Najpierw pełny z weekendu, następnie wszystkie po kolei kopie dziennika transakcji wykonane po pełnym.",
      "correct": false
    },
    {
      "answer": "Najpierw pełny z weekendu, a następnie log ze środy z godz. 12:00.",
      "correct": false
    },
    {
      "answer": "Nie da się odtworzyć tej bazy, gdyż brakuje kopii różnicowej.",
      "correct": false
    },
    {
      "answer": "Najpierw pełny, a następnie wszystkie logi wykonane od ostatniego restartu serwera.",
      "correct": false
    }
  ],
  "id": "z-13-316a3e87-45b8-4a87-be3d-9b9f83cb63ce",
  "createdAt": 1657199812909,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/tak/1932.patch.json
{
  "id": "1932",
  "question": "Aby określić złożoność pesymistyczną algorytmu musimy odnieść ją do:",
  "answers": [
    {
      "answer": "wszystkich możliwych do wyobrażenia algorytmów",
      "correct": false
    },
    {
      "answer": "wszystkich możliwych danych",
      "correct": true
    },
    {
      "answer": "konkretnych danych",
      "correct": true
    },
    {
      "answer": "konkretnego rozkladu pewnej zmiennej losowej",
      "correct": false
    }
  ],
  "createdAt": 1673385234728,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-21-8b4e8809-611b-43b0-85b4-62fac5def066.patch.json
{
  "question": "To create a class method in Java, use the class keyword.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "In Java, class methods are created using the static keyword.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-21-8b4e8809-611b-43b0-85b4-62fac5def066",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/tin/z-03-431f8064-d5a5-4875-93c8-c4cfa44e3b53.patch.json
{
  "question": "Numery portów są przekazywane w ramach:",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "protokołu aplikacyjnego",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "protokołu warstwy sprzętowej",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "protokołu transportowego",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "protokołu warstwy sieciowej",
      "correct": false,
      "isMarkdown": false
    }
  ],
  "id": "z-03-431f8064-d5a5-4875-93c8-c4cfa44e3b53",
  "createdAt": 1707434565194,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-35-2607d73c-63c0-4003-bb89-c08f279f7739.patch.json
{
  "question": "Hashtable is one of several possible classes that can store a lot of extents in Java.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Hashtable is one of the Map interface implementations that is convenient for storing multiple extents.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-35-2607d73c-63c0-4003-bb89-c08f279f7739",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}
