=== horno1337/zdaj-se-pjatk-data/schemas/subject-patch.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "subject-patch",
  "title": "Data Item",
  "type": "object",
  "properties": {
    "question": {
      "$id": "#root/question",
      "title": "Question",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": 0
    },
    "numberOfComments": {
      "$id": "#root/numberOfComments",
      "title": "Number of Comments",
      "type": "integer",
      "default": 0
    },
    "answers": {
      "$id": "#root/answers",
      "title": "Answers",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/answers/items",
        "title": "Items",
        "type": "object",
        "required": ["answer", "correct"],
        "properties": {
          "answer": {
            "$id": "#root/answers/items/answer",
            "title": "Answer",
            "type": "string",
            "default": ""
          },
          "correct": {
            "$id": "#root/answers/items/correct",
            "title": "Correct",
            "type": "boolean",
            "default": true
          },
          "isMarkdown": {
            "$id": "#root/answers/items/isMarkdown",
            "title": "Is Markdown",
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
          }
        },
        "required": ["author", "comment", "date"]
      }
    },
    "contributors": {
      "$id": "#root/contributors",
      "title": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "createdAt": {
      "$id": "#root/createdAt",
      "title": "Created At",
      "type": "integer",
      "default": 0
    },
    "isMarkdown": {
      "$id": "#root/isMarkdown",
      "title": "Is Markdown",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["question", "id", "createdAt"]
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/sbd/2384.patch.json
{
  "question": "Wskazać poprawne zapytanie SQL (w Oracle) znajdujące stanowiska, na których średni zarobek wynosi 3000 lub więcej.",
  "id": "2384",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "```sql\nSELECT job, AVG(sal) FROM emp HAVING AVG (sal) >= 3000 GROUP BY job\n```",
      "correct": true,
      "isMarkdown": true
    },
    {
      "answer": "```sql\nSELECT job, AVG(sal) FROM emp GROUP BY job WHERE AVG (sal) >= 3000\n```",
      "correct": false,
      "isMarkdown": true
    },
    {
      "answer": "```sql\nSELECT job, AVG(sal) FROM emp WHERE AVG (sal) >= 3000 GROUP BY job\n```",
      "correct": false,
      "isMarkdown": true
    },
    {
      "answer": "```sql\nSELECT job, AVG(sal) FROM emp GROUP BY job HAVING AVG (sal) >= 3000\n```",
      "correct": true,
      "isMarkdown": true
    }
  ],
  "createdAt": 1707647448640,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-148-9054998a-392a-4b66-a3fe-a2f8ea0afa8f.patch.json
{
  "question": "The workload needed to create your own GUI library is comparable to that required for existing modification.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Modifying an existing library is a lot simpler than creating your own from scratch.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-148-9054998a-392a-4b66-a3fe-a2f8ea0afa8f",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-64-51415045-3531-4784-82c7-aa213d107467.patch.json
{
  "question": "The most precise way to write constraints is the natural language.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Unfortunately, natural language is one of the least restrictive ways of defining constraints",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-64-51415045-3531-4784-82c7-aa213d107467",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-157-38568726-3622-4f4a-aed9-ae495ecf7cd9.patch.json
{
  "question": "The ProgressWorker class displays the progress bar.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "One of the improvements to the ProgressWorker is to add a progress bar.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-157-38568726-3622-4f4a-aed9-ae495ecf7cd9",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-39-5350dab1-dbfc-4313-a640-8b723e0e76c9.patch.json
{
  "question": "Correctly defined cardinalities reduce the risk of making an error.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "One of the reasons for defining cardinalities is the ability to control them by implementing business rules.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-39-5350dab1-dbfc-4313-a640-8b723e0e76c9",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-92-d4cb3081-681f-4923-bafe-75b006aed3b7.patch.json
{
  "question": "Complex attributes can be implemented in RM as a separate table with a foreign key.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "One way to implement complex attributes is to use an external table with the foreign key.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-92-d4cb3081-681f-4923-bafe-75b006aed3b7",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-87-2c906331-fbbc-49df-ac02-ad3b0807a810.patch.json
{
  "question": "Classes are mapped to relational tables.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "In fact, classes are mapped to relational tebels.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-87-2c906331-fbbc-49df-ac02-ad3b0807a810",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}

=== horno1337/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-59-19c0f53f-34d1-4656-b029-cefde57dca2f.patch.json
{
  "question": "The simplest way to implement multi-aspect inheritance is to flatten the hierarchy.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Flattening of the hierarchy is the easiest way to implement any kind of inheritance (including multi-aspect).",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-59-19c0f53f-34d1-4656-b029-cefde57dca2f",
  "createdAt": 1691363367006,
  "$schema": "../../../schemas/subject-patch.json"
}
